chore!: rename to editorconfig-checker
editorconfig-checker/editorconfig-checker pull request #255
Opened 2023-02-15 00:25 UTC by jay-babu

2023-02-17 00:15 UTC, jay-babu commented
Closes: https://github.com/editorconfig-checker/editorconfig-checker/issues/232

2024-02-01 19:47 UTC, theoludwig requested changes
Thank you for the PR! :smile:

If we rename the command to `editorconfig-checker` instead of `ec`, we should also replace all occurrences of `ec` in the README.

2024-09-05 21:14 UTC, klaernie commented
hm.. that change in README.md would only be two lines - Should I rebase @jay-babu's commit, add that small change and open a new PR?

2024-09-06 15:56 UTC, klaernie commented
done in #371

2025-01-08 17:30 UTC, closed without merging